# Disable parallelism when using Vagrant commands
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Ensure Vagrant version is at least 2.0.0
Vagrant.require_version ">=2.0.0"

# Function to install a Vagrant plugin if it's not already installed
def install_vagrant_plugin(name)
  unless Vagrant.has_plugin?(name)
    # Install the plugin using system command
    system("vagrant plugin install #{name}")
    # Restart the Vagrant command with the original arguments
    exec "vagrant #{ARGV.join(' ')}"
  end
end

# Vagrant configuration block
Vagrant.configure("2") do |config|
  # Install the "vagrant-disksize" plugin
  install_vagrant_plugin("vagrant-disksize")

  # Set the base box to "ubuntu/focal64"
  config.vm.box = "ubuntu/focal64"

  # Disable box update checks
  config.vm.box_check_update = false

  # Disable base MAC address setting
  config.vm.base_mac = nil

  # Set the disk size to 50GB
  config.disksize.size = '50GB'

  # Provision the VM using a shell script named "bootstrap.sh"
  config.vm.provision "shell", path: "bootstrap.sh"

  # Provider-specific configuration for VirtualBox
  config.vm.provider :virtualbox do |vb|
    # Set memory to 2048 MB
    vb.memory = 2048

    # Set number of CPUs to 2
    vb.cpus = 2

    # Enable NAT DNS host resolver
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # Enable I/O Advanced Programmable Interrupt Controller (IOAPIC)
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Create three virtual machines with a private network and custom hostnames
  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      # Disable box update checks for each node
      node.vm.box_check_update = false

      # Set the hostname for each node as "node-1", "node-2", "node-3"
      node.vm.hostname = "node-#{i}"

      # Create a private network with custom IP addresses (172.16.0.11, 172.16.0.12, 172.16.0.13)
      node.vm.network "private_network", ip: "172.16.0.1#{i}"

      # Provider-specific configuration for VirtualBox for each node
      node.vm.provider "virtualbox" do |vb|
        # Set custom VM name as "node-1", "node-2", "node-3"
        vb.name = "node-#{i}"
      end
    end
  end
end
